cp ../styles/american-chemical-society.csl styles/
cp ../styles/american-medical-association.csl styles/
cp ../styles/american-political-science-association.csl styles/
cp ../styles/apa.csl styles/
cp ../styles/american-sociological-association.csl styles/
cp ../styles/chicago-author-date.csl styles/
cp ../styles/chicago-note-bibliography.csl styles/
cp ../styles/chicago-fullnote-bibliography.csl styles/
cp ../styles/harvard-cite-them-right.csl styles/
cp ../styles/elsevier-harvard.csl styles/
cp ../styles/ieee.csl styles/
cp ../styles/modern-humanities-research-association.csl styles/
cp ../styles/modern-language-association.csl styles/
cp ../styles/nature.csl styles/
cp ../styles/vancouver.csl styles/
